# Generated by Django 3.2.5 on 2022-04-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermana',
            name='FechaDeNacimiento',
            field=models.CharField(default=16031995, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hermano',
            name='FechaDeNacimiento',
            field=models.CharField(default=20041986, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mama',
            name='FechaDeNacimiento',
            field=models.CharField(default=29061964, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='FechaDeNacimiento',
            field=models.CharField(default=12112017, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novia',
            name='FechaDeNacimiento',
            field=models.CharField(default=20021995, max_length=10),
            preserve_default=False,
        ),
    ]
