# Generated by Django 3.2.5 on 2022-04-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20220402_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hermana',
            new_name='Familiares',
        ),
        migrations.DeleteModel(
            name='Hermano',
        ),
        migrations.DeleteModel(
            name='Mama',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Novia',
        ),
    ]
